# Use an official Node.js runtime as the base image
FROM node:20.4

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the entire frontend application code to the working directory
COPY . .

# Build the frontend application
RUN npm run build

# Expose the container port
EXPOSE 3000

# Define the command to start the frontend application
CMD ["npm", "start"]
